$schema: https://json-schema.org/draft/2020-12/schema
$id: https://schemas.example/conformance/root/
$ref: child/#/$defs/payload
$defs:
  child:
    $id: child/
    $defs:
      payload:
        type: object
        required:
        - title
        properties:
          title:
            type: string
