"""Soft schema conventions and validation tools for Markdown/YAML artifacts."""

from __future__ import annotations

from softschema.canonicalize import apply_enforced_extras, canonicalize_json_schema
from softschema.compile import SOFTSCHEMA_FORMAT_VERSION, CompileResult, compile_model
from softschema.generate import GeneratedSection, RegenerateResult, regenerate
from softschema.models import (
    Contract,
    SchemaMetadata,
    SchemaProfile,
    SchemaStatus,
    SchemaWarning,
    WarningCode,
    parse_schema_metadata,
    validate_contract_id,
    validate_extension_namespace,
    validate_schema_id,
)
from softschema.registry import Contracts
from softschema.schema_view import FieldInfo, SchemaView
from softschema.soft_field import (
    RepairKind,
    SoftField,
    SoftFieldMeta,
    SoftOwner,
    SoftTier,
)
from softschema.validate import (
    ArtifactFrontmatterError,
    ArtifactInputReason,
    ArtifactParseReason,
    ArtifactRootError,
    ArtifactValidationResult,
    EnvelopeAmbiguityError,
    SchemaResource,
    SchemaResources,
    SemanticResult,
    StructuralResult,
    ValidationResult,
    artifact_error_record,
    artifact_input_error_record,
    artifact_parse_error_record,
    infer_envelope_key,
    read_frontmatter,
    read_yaml_artifact,
    validate_artifact,
    validate_semantic,
    validate_structural,
    validate_values,
)
from softschema.value_domain import DEFAULT_VALIDATION_LIMITS, ValidationLimits

__all__ = [
    "DEFAULT_VALIDATION_LIMITS",
    "SOFTSCHEMA_FORMAT_VERSION",
    "ArtifactFrontmatterError",
    "ArtifactInputReason",
    "ArtifactParseReason",
    "ArtifactRootError",
    "ArtifactValidationResult",
    "CompileResult",
    "Contract",
    "Contracts",
    "EnvelopeAmbiguityError",
    "FieldInfo",
    "GeneratedSection",
    "RegenerateResult",
    "RepairKind",
    "SchemaMetadata",
    "SchemaProfile",
    "SchemaResource",
    "SchemaResources",
    "SchemaStatus",
    "SchemaView",
    "SchemaWarning",
    "SemanticResult",
    "SoftField",
    "SoftFieldMeta",
    "SoftOwner",
    "SoftTier",
    "StructuralResult",
    "ValidationLimits",
    "ValidationResult",
    "WarningCode",
    "apply_enforced_extras",
    "artifact_error_record",
    "artifact_input_error_record",
    "artifact_parse_error_record",
    "canonicalize_json_schema",
    "compile_model",
    "infer_envelope_key",
    "parse_schema_metadata",
    "read_frontmatter",
    "read_yaml_artifact",
    "regenerate",
    "validate_artifact",
    "validate_contract_id",
    "validate_extension_namespace",
    "validate_schema_id",
    "validate_semantic",
    "validate_structural",
    "validate_values",
]
