/**
 * Runtime-neutral softschema contract core.
 *
 * This entrypoint accepts and returns JSON-compatible values. It does not parse YAML,
 * touch the filesystem, load Zod models, dynamically import code, or implement a CLI.
 */
export {
  applyEnforcedExtras,
  canonicalizeJsonSchema,
  ENFORCEMENT_UNSUPPORTED_MESSAGE,
  EnforcementUnsupportedError,
} from "../canonicalize.js";
export {
  type EnforcementUnsupportedErrorRecord,
  renderStructuralMessage,
  type SchemaInvalidErrorRecord,
  type SchemaInvalidReason,
  type SchemaViolationErrorRecord,
  type StructuralErrorRecord,
  schemaInvalidError,
  structuralErrorRecord,
} from "../errors.js";
export {
  type Contract,
  type ContractDescriptor,
  type ContractWire,
  contractToOutput,
  defineContract,
  defineContractDescriptor,
  isSchemaStatus,
  metadataToOutput,
  parseSchemaMetadata,
  pyTypeName,
  type SchemaMetadata,
  SchemaMetadataError,
  type SchemaMetadataWire,
  type SchemaProfile,
  type SchemaStatus,
  type SchemaWarning,
  validateContractId,
  validateExtensionNamespace,
  validateSchemaId,
  type WarningCode,
} from "../models.js";
export {
  firstUnsupportedPattern,
  isPortablePattern,
  PORTABLE_PATTERN_MAX_CODEPOINTS,
  PORTABLE_PATTERN_MAX_DFA_STATES,
  PORTABLE_PATTERN_MAX_DFA_TRANSITIONS,
  PORTABLE_PATTERN_MAX_GROUP_DEPTH,
  PORTABLE_PATTERN_MAX_MATCH_COMPUTE_WORK,
  PORTABLE_PATTERN_MAX_NFA_STATES,
  PORTABLE_PATTERN_MAX_QUANTIFIER,
  PORTABLE_PATTERN_MAX_SCHEMA_CODEPOINTS,
  PORTABLE_PATTERN_MAX_SCHEMA_PATTERNS,
  PORTABLE_PATTERN_MAX_VALIDATION_WORK,
  PORTABLE_PATTERN_PROFILE,
  PortablePatternError,
  PortablePatternWorkLimitError,
  portablePatternMatches,
  type UnsupportedPattern,
} from "../portable-pattern.js";
export { Contracts } from "../registry.js";
export { canonicalJson, stableStringify } from "./canonical-json.js";
export {
  DIAGNOSTIC_FORMAT,
  type DiagnosticAggregateV1,
  type DiagnosticCategory,
  type DiagnosticJsonlRecordV1,
  type DiagnosticLimitsWire,
  type DiagnosticOutcome,
  type DiagnosticResultV1,
  type DiagnosticRuleFamily,
  type DiagnosticSeverity,
  type DiagnosticSummaryV1,
  type DiagnosticV1,
  type DiagnosticValidationWire,
  type DiagnosticWarningWire,
  diagnosticRuleId,
  projectDiagnosticAggregate,
  projectDiagnosticResult,
  projectDiagnosticSarif,
  projectValidationWire,
  SARIF_SCHEMA_URI,
  SARIF_VERSION,
  serializeDiagnosticJsonl,
  validationLimitsWire,
} from "./diagnostics.js";
export { EnvelopeAmbiguityError, inferEnvelopeKey } from "./envelope.js";
export type {
  ArtifactInputErrorRecord,
  ArtifactInputReason,
  ArtifactInputResult,
  ArtifactInputSuccessResult,
  ArtifactParseErrorRecord,
  ArtifactParseReason,
  ArtifactStructuralErrorKind,
  ArtifactStructuralErrorRecord,
  ArtifactValidationResult,
  JsonPathSegment,
  MetadataMode,
  RawFrontmatter,
  SchemaResource,
  SchemaResources,
  SemanticIssue,
  SemanticResult,
  StructuralErrorWire,
  StructuralIssue,
  StructuralResult,
  ValidationResult,
  ValidationResultLegacyWire,
} from "./results.js";
export {
  jsonPointer,
  type NodeSource,
  type SourceAnchor,
  SourceMap,
  type SourcePoint,
  type SourceSpan,
} from "./source-map.js";
export {
  canonicalPortableJsonSize,
  DEFAULT_VALIDATION_LIMITS,
  type JsonObject,
  type JsonValue,
  type NormalizedValue,
  normalizePortableValue,
  PortableValueError,
  PortableYamlError,
  resolveValidationLimits,
  type ValidationLimitOverrides,
  type ValidationLimits,
} from "./value-domain.js";
